name: Java CI with Maven

on:
  push:
    branches: [ "main", "master" ]
  pull_request: #trigger khi có pull requestt
    branches: [ "main", "master" ]

jobs:
  build:
    # 1. Định nghĩa ma trận hệ điều hành
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    # 2. Sử dụng biến os từ ma trận
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build and Test Bai03
      # Dùng lệnh chạy phù hợp với mọi OS
      run: mvn -f Bai03/pom.xml clean package 

    - name: Upload Artifact
      # Chỉ upload artifact từ máy Ubuntu để tránh bị trùng lặp
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: math-utils-build
        path: Bai03/target/*.jar
    - name: Build and Verify with JaCoCo
      # Thay 'package' bằng 'verify' để kích hoạt bước check coverage của JaCoCo
      run: mvn -f Bai03/pom.xml clean verify 

    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        # Đường dẫn đến file báo cáo (dạng HTML)
        path: Bai03/target/site/jacoco/
    # Bai07 Inline Feedback (Sử dụng Reviewdog cực kỳ ổn định)
    - name: Checkstyle Review
      if: always() && github.event_name == 'pull_request' # Chỉ chạy khi là PR
      uses: reviewdog/action-checkstyle@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review # Ép Bot phải viết comment vào PR
        level: error
        checkstyle_config: google_checks.xml



